import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google'; // Import the 'Montserrat' font
import { FaInstagram, FaFacebookF, FaLinkedinIn,FaTwitter } from 'react-icons/fa';

const montserrat = Montserrat({ subsets: ['latin'] }); // Create a font instance for 'Montserrat'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
        {/* Add your styled footer here */}
        <footer className="bg-gray-800 text-white p-4">
          <div className="container mx-auto pr-20">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="col-span-2 md:col-span-1 pr-10">
                <h2 className="text-2xl font-bold mb-2">
                  get<span className='text-purple-600'>linked</span>
                </h2>
                <p>
                  Getlinked Tech Hackathon is a technology innovation program
                  <br /> established by a group of organizations with the aim of showcasing
                  <br /> young and talented individuals in the field of technology
                </p>
                <br />
                <br />
                <br />
                <br />
                <div className='flex gap-3'>
                  <p>Terms of use</p>
                  <div className='line bg-purple-600'></div>Privacy Policy
                </div>
                
              </div>
              <div className="col-span-2 md:col-span-1 ml-40 leading-10">
                <h3 className="text-xl font-semibold mb-2 text-purple-600">Useful Links</h3>
                <p>Overview</p>
                <p>Timeline</p>
                <p>FAQ</p>
                <p>Register</p>
                <div className='flex flex-row items-center'> {/* Use flex for icon and text alignment */}
                  <h3 className='text-purple-600 font-bold'>Socials&nbsp;&nbsp;&nbsp;</h3>
                  <div className='flex items-center gap-2'> {/* Add items-center to align the icons vertically */}
                    <FaInstagram />
                    <FaFacebookF />
                    <FaLinkedinIn />&nbsp;
                    <FaTwitter />
                  </div>
                </div>
              </div>
              <div className="col-span-2 md:col-span-1 ml-32">
                <h3 className="text-xl font-semibold mb-2 text-purple-600">Contact Us</h3>
                <div className='flex flex-row items-center'> {/* Use flex for icon and text alignment */}
                  <span className='text-white font-bold'>&#9743;&nbsp;&nbsp;&nbsp;</span>
                  <div className='flex items-center gap-2 text-purple-600'> {/* Add items-center to align the icons vertically */}
                    +234 7027188290
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className=' text-center justify-center'>
                  <p>All rights reserved. &copy; getlinked Ltd.</p>
                </div>
        </footer>
      </body>
    </html>
  )
}
